// Flight details
export const FETCH_FLIGHT_DETAILS = 'FETCH_FLIGHT_DETAILS';
export const FETCH_FLIGHT_DETAILS_SUCCESS = 'FETCH_FLIGHT_DETAILS_SUCCESS';
export const FETCH_FLIGHT_DETAILS_ERROR = 'FETCH_FLIGHT_DETAILS_ERROR';
export const EDIT_FLIGHT_DETAILS = 'EDIT_FLIGHT_DETAILS';
export const EDIT_FLIGHT_DETAILS_SUCCESS = 'EDIT_FLIGHT_DETAILS_SUCCESS';
export const EDIT_FLIGHT_DETAILS_ERROR = 'EDIT_FLIGHT_DETAILS_ERROR';
export const CREATE_FLIGHT_DETAILS = 'CREATE_FLIGHT_DETAILS';
export const CREATE_FLIGHT_DETAILS_SUCCESS = 'CREATE_FLIGHT_DETAILS_SUCCESS';
export const CREATE_FLIGHT_DETAILS_ERROR = 'CREATE_FLIGHT_DETAILS_ERROR';

// Airports
export const FETCH_AIRPORTS = 'FETCH_AIRPORTS';
export const FETCH_AIRPORTS_SUCCESS = 'FETCH_AIRPORTS_SUCCESS';
export const FETCH_AIRPORTS_ERROR = 'FETCH_AIRPORTS_ERROR';
