// Flights
export const FETCH_FLIGHTS = 'FETCH_FLIGHTS';
export const FETCH_FLIGHTS_SUCCESS = 'FETCH_FLIGHTS_SUCCESS';
export const FETCH_FLIGHTS_ERROR = 'FETCH_FLIGHTS_ERROR';
export const DELETE_FLIGHT = 'DELETE_FLIGHT';
export const DELETE_FLIGHT_SUCCESS = 'DELETE_FLIGHT_SUCCESS';
export const DELETE_FLIGHT_ERROR = 'DELETE_FLIGHT_ERROR';

// Services
export const FETCH_SERVICES = 'FETCH_SERVICES';
export const FETCH_SERVICES_SUCCESS = 'FETCH_SERVICES_SUCCESS';
export const FETCH_SERVICES_ERROR = 'FETCH_SERVICES_ERROR';
